/kf_tracker_node:
  ros__parameters:
    # Rate of prediction step
    dt_pred: 0.02
    print_debug_msg: False

    # Diagonal elements of the process covariance matrix Q, for constant acceleration model
    # [x-x, y-y, z-z, vx-vx, vy-vy, vz-vz, ax-ax, ay-ay, az-az]
    # NOT USED
    q_diag: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ,0.1 , 0.1, 0.1]

    # Diagonal elements of the process covariance matrix Q, for constant velocity model
    # # [x-x, y-y, z-z, vx-vx, vy-vy, vz-vz]
    # NOT USED
    # q_diag: [5,5,5,10,10,10]

    # Diagonal elements of the process covariance matrix Q, for constant velocity or acceleration models
    # Also used in initializing the upper left (position) part of the P matrix (process covariance) for a track
    r_diag: [1., 1., 1.]

    # Standard deviation of the random acceleration variable.
    # Used in computing Q matrix
    sigma_a: 200.0

    # Standard deviation of position
    # Used in computing initial P (state estimate covariance) matrix
    sigma_p: 1.0
    # Standard deviation of velocity
    # Used in computing initial P (state estimate covariance) matrix
    sigma_v: 1.0

    # Provide estimate w.r.t this frame
    tracking_frame: 'interceptor/odom'
    # Topic name of the tag detections
    apriltags_topic: '/tag_detections'
    # Frame name of the detected target
    target_frameid: 'tag'

    # Get target measurements from TF tree
    listen_tf: False

    # Maximum uncertainty before rejecting a track [m^3] 
    V_max: 100.0
    # Minimum uncertainty for confirming a track [m^3]
    V_certain: 30.0
    # Minimum number of measurements to confirm a track
    N_meas: 10
    # Measurement association log-likelihood threshold
    l_threshold: -100.0

    # Maximum distance between  a state & measurement to consider them as a match (currently not used)
    dist_threshold: 5.0

    # False: Doesn't consider measurement track ID in measurement-state association 
    use_track_id: false

    # Maximum time (seconds) from last measurement before considering a track uncertain and removing it
    track_mesurement_timeout: 3.0